baseURL: "https://mkjuergens.github.io/"
title: Mira Jürgens
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 3
        - name: Talks
          url: talks/
          weight: 4
        - name: Teaching
          url: teaching/
          weight: 5
        - name: Blog
          url: blog/
          weight: 6

params:
    description: "Mira Juergens personal website."
    author: Mira Juergens
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","talks","teaching", "blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mira Jürgens
          subtitle: "I am a PhD candidate at Ghent University, Belgium. My research focuses on how to quantify and represent uncertainty in machine learning, as well as how to develop actionable decision from it.
            I am particularly interested in the proper evaluation of uncertainty representations as well as the application of uncertainty-aware prediction pipelines to real-world problems."
          imageUrl: "mira7.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Talks
              url: talks/
            - name: Blog
              url: blog/
            - name: Teaching 
              url: teaching/

    socialIcons:
        # - name: CV
        #   url: cv.pdf # to do
        - name: Email
          url: mailto:mira.kjuergens@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=zZ1wk94AAAAJ&hl=de
        - name: GitHub
          url: https://github.com/mkjuergens

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Mira Jürgens"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2